INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2017-08-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 149.8, '2017-08-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 455.77, '2017-08-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 244.17, '2017-08-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 629.32, '2017-08-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 549.17, '2017-08-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 695.81, '2017-08-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 49.36, '2017-08-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2017-08-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 859.41, '2017-08-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 730.18, '2017-08-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 923.75, '2017-08-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2017-09-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 387.45, '2017-09-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 257, '2017-09-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 540.77, '2017-09-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 224.09, '2017-09-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 764.62, '2017-09-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 543.04, '2017-09-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 752.16, '2017-09-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2017-09-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 556.86, '2017-09-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 267.64, '2017-09-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 0.9496, '2017-09-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2017-10-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 220.73, '2017-10-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 183.73, '2017-10-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 586.4, '2017-10-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 765.31, '2017-10-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 952.79, '2017-10-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 840.92, '2017-10-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 818.86, '2017-10-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2017-10-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 430.92, '2017-10-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 847.59, '2017-10-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 116.05, '2017-10-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2017-11-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 299.87, '2017-11-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 397.35, '2017-11-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 444.98, '2017-11-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 202.74, '2017-11-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 822.17, '2017-11-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 549.52, '2017-11-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 365.73, '2017-11-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2017-11-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 581.09, '2017-11-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 99.17, '2017-11-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 496.42, '2017-11-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2017-12-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 660.61, '2017-12-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 801.11, '2017-12-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 476.84, '2017-12-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 392.27, '2017-12-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 33.806, '2017-12-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 742.26, '2017-12-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 809.66, '2017-12-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2017-12-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 319.7, '2017-12-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 543.3, '2017-12-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 975.91, '2017-12-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2018-01-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 253.74, '2018-01-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 702.22, '2018-01-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 2.1678, '2018-01-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 236.15, '2018-01-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 677.13, '2018-01-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 111.56, '2018-01-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 375.55, '2018-01-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2018-01-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 707.6, '2018-01-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 28.988, '2018-01-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 212.73, '2018-01-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2018-02-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 722.53, '2018-02-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 324.83, '2018-02-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 112.06, '2018-02-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 920.42, '2018-02-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 477.22, '2018-02-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 436.26, '2018-02-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 569.81, '2018-02-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 1330, '2018-02-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 632.78, '2018-02-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 109.35, '2018-02-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 58.275, '2018-02-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2018-03-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 731.69, '2018-03-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Passeio', 'D', 'LAZER', 709, '2018-03-07');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de telefone e internet', 'D', 'CONTAS', 213.07, '2018-03-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Conta de luz', 'D', 'CONTAS', 263.79, '2018-03-10');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Consulta médica', 'D', 'SAUDE', 460.86, '2018-03-12');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Faculdade', 'D', 'EDUCACAO', 998.97, '2018-03-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Condomínio', 'D', 'CONTAS', 959.57, '2018-03-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Recebimento de aluguel', 'R', 'ALUGUEL', 970.31, '2018-03-15');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Combustível', 'D', 'LOCOMOCAO', 311.63, '2018-03-20');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Presente', 'D', 'OUTROS', 291.89, '2018-03-23');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 981.43, '2018-03-26');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Salario', 'R', 'SALARIO', 3410.34, '2018-04-03');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'ALIMENTACAO', 731.69, '2018-04-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'EDUCACAO', 329.11, '2018-04-04');
INSERT INTO public.lancamentos(id_usuario, descricao, tipo, natureza, valor, data)	VALUES (44, 'Mercado', 'D', 'LOMOCOCAO', 155.33, '2018-04-04');



